### ISSUE TITLE
I can't use your Extension, help me pls

### ISSUE THREAD

**Issue by nuengcpe** [himiklab/yii2-jqgrid-widget#2]
I'm newbie in yii2 ,I  install extension with composer and I have himiklab folder in vendor,I tried to use this extension from example but not work! when i call jqgrid  
I have error "Invalid Configuration – yii\base\InvalidConfigException
Object configuration must be an array containing a "class" element."

siteController 

 public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],

```
          'jqgrid' => [
           'class' => JqGridActiveAction::className(),
            'model' => Page::className(),
            'columns' => ['title', 'author', 'language']
        ],
    ];
}
```

**Comment by vishwasrao** [comment]
Thanks,It worked for me also..
