### ISSUE TITLE
Problem installing extension through composer

### ISSUE THREAD

**Issue by XuriDabur** [himiklab/yii2-jqgrid-widget#3]
(Cross-post from http://www.yiiframework.com/forum/index.php/topic/61776-getting-himiklabs-gridjs-widget-for-yii2-working/ )

When trying to install yii2-jqgrid-widget through composer, by adding the following line to my composer.json - **"himiklab/yii2-jqgrid-widget" : "*"** - (with minimum stability "stable") and running composer update, I am greeted with a problem message:

> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - himiklab/yii2-jqgrid-widget 1.0.8 requires bower-asset/jqgrid 4.7.0 -> no matching package found.
> - himiklab/yii2-jqgrid-widget 1.0.7 requires bower-asset/jqgrid 4.7.0 -> no matching package found.
> - Installation request for himiklab/yii2-jqgrid-widget * -> satisfiable by himiklab/yii2-jqgrid-widget[1.0.7, 1.0.8].

**Comment by himiklab** [comment]
Try updating composer-asset-plugin:
```php
php composer.phar global require "fxp/composer-asset-plugin:1.0.0"
```

**Comment by XuriDabur** [comment]
Thank you. That fixed the problem. Now I just have to figure out why I get an internal 500 server error when I try to use the widget while the *public function actions()* function from documentation is present in my controller ^^;

**Comment by himiklab** [comment]
Thank you, I will fix it!

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-jqgrid-widget/commit/9762ce381a6306a601406a6ff6f8cfbfa5ccd804
