### ISSUE TITLE
SqlDataProvider action

### ISSUE THREAD

**Issue by servocoder** [himiklab/yii2-jqgrid-widget#7]
Hey, do you plan to implement an action for SqlDataProvider?

**Comment by servocoder** [comment]
Уже решил через ArrayAction, лично мне уже не актуально :)

**Comment by himiklab** [comment]
Понятно, может когда-то напишу, хотя не вижу особого смысла уже реализованным JqGridArrayAction.

**Comment by servocoder** [comment]
В целом да, можно обойтись.
